export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const STORE_STUDENT_DETAILS = 'STORE_STUDENT_DETAILS';
export const STORE_STUDENT_EDUCATION_DETAILS = 'STORE_STUDENT_EDUCATION_DETAILS';
export const STORE_STUDENT_EXPERIENCE_DETAILS = 'STORE_STUDENT_EXPERIENCE_DETAILS';
export const STORE_CONTROL_MODAL = 'STORE_CONTROL_MODAL';
